# Generated by Django 3.2.9 on 2021-12-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='device',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
