# Generated by Django 3.2.9 on 2021-12-03 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20211202_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(blank=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first.devicenumber'),
        ),
    ]
